#! /bin/sh
# statistic of dwi
#

Usage () {
 cat << EOF

 Perform statistics of dwi data

   Usage: $0 <dwi.nii> <bvals> <outputrootname> [mask]

   Print number of b=0 volumes and SNR.

EOF
 exit 1;
}

[ "$1" =  "" ] && Usage

dwi=$1
bval=$2
out=$3
mask=$4
tmp=tmp_$$

b0="";j=0;for i in `cat $bval`; do if [ "`echo $i | awk '{if ($1<=20) print}'`" != "" ] ; then b0="$b0 $j";fi;j=`expr $j + 1`; done
for i in $b0; do
  j=`zeropad $i 4`
  fslroi ${dwi} ${tmp}_${j} $i 1
done
num=`imglob -onerperimage ${tmp}_* | wc -w`
if [ "$num" = 0 ] ; then echo "Error: Cannot find b0 volumes"; exit 1;fi

fslmerge -t ${tmp}_merge `imglob -onerperimage ${tmp}_*`
fslmaths ${tmp}_merge -Tmean ${out}_mean -odt float
fslmaths ${tmp}_merge -Tstd ${out}_std -odt float
fslmaths ${out}_mean -div ${out}_std ${out}_snr -odt float
if [ "$4" != "" ] ; then
  mask=$4
else
  bet ${out}_mean ${out}_mean_brain -m -f 0.2
  mask=${out}_mean_brain_mask
fi

fslmaths ${out}_mean -mas $mask ${out}_mean
fslmaths ${out}_snr -mas $mask ${out}_snr
fslmaths ${out}_std -mas $mask ${out}_std
snr=`fslstats ${out}_snr -k  ${mask} -M`

echo "$num $snr"
rm -rf $tmp; imrm ${tmp}*

exit 0;
