#! /bin/sh
# statistic of dwi

# This script will be running on the directory you are in.
# Thus, you should generate tmp-dir and change directory before running the code below.

Usage () {
 cat << EOF

 Perform statistics of dwi data

   Usage: $0 <dwi.nii> <bvals> <outputrootname> <mask> [b0 threshold]

   Print number of b=0 volumes and SNR. Default b0 threshold is 20.

EOF
 exit 1;
}

[ "$1" =  "" ] && Usage

dwi=$1
bval=$2
out=$3
mask=$4
if [ "$5" != "" ] ; then
	b0thresh=$5
else
	b0thresh=20
fi
tmp=tmp_$$

echo ${tmp}
echo $(pwd)

j=0;
for i in `cat $bval`; do
	if [ `echo $i | awk '{printf "%d",$1}'` -le $b0thresh ] ; then
		echo "Found b=0 volume at tdim=$j"
    fslroi ${dwi} ${tmp}_`zeropad $j 4` $j 1
	fi;
	j=`expr $j + 1`;
done

echo $(pwd)
ls ${tmp}*

num=`imglob -extension ${tmp}_????.nii.gz | wc -w`
if [ $num = 0 ] ; then echo "ERROR: Cannot find b0 volumes"; exit 1;fi

fslmerge -t ${tmp}_merge `imglob -extension ${tmp}_????.nii.gz`
fslmaths ${tmp}_merge -Tmean ${out}_mean -odt float
fslmaths ${tmp}_merge -Tstd ${out}_std -odt float
fslmaths ${out}_mean -div ${out}_std ${out}_snr -odt float
fslmaths ${out}_mean -mas $mask ${out}_mean
fslmaths ${out}_snr -mas $mask ${out}_snr
fslmaths ${out}_std -mas $mask ${out}_std
snr=`fslstats ${out}_snr -k  ${mask} -M`

echo "Number of b0 volume: $num, b0 tSNR: $snr"
imrm ${tmp}_*

exit 0;
